"""Analysis utilities for TVBToolkit."""

from tvbtoolkit.analysis.brain_states import (
    BrainStateSummary,
    brain_state_metrics_dict,
    centers_to_matrices,
    cluster_brain_states,
    phase_patterns,
    sfc_sort_centroids,
    summarize_brain_states,
)
from tvbtoolkit.analysis.spectral import (
    PSDResult,
    ValidityResult,
    dominant_frequency,
    phase_coherence_validity,
    psd_per_region,
)
from tvbtoolkit.analysis.state_alignment import (
    AlignmentResult,
    align_states_to_templates,
    centroid_similarity_matrix,
    fit_state_templates,
    safe_pearson,
)
from tvbtoolkit.analysis.dynamics import load_survival_arrays, plot_survival_heatmap
from tvbtoolkit.analysis.phiid import (
    LEGACY_REFERENCE_PATHS,
    PHIID_ATOMS,
    PRIMARY_ATOMS,
    PUBLICATION_COHORT_ORDER,
    average_atom_matrices_by_group,
    build_matlab_batch_command,
    default_atom_cmap,
    compact_roi_labels,
    export_phiid_subject_inputs,
    format_roi_label_compact,
    load_phiid_index,
    load_phiid_matrix,
    parse_phiid_output_name,
    plot_group_average_grid,
    plot_publication_cohort_grid,
    plot_publication_method_comparison_grid,
    plot_phiid_matrix,
    publication_atom_cmap,
    save_group_average_outputs,
    sanitize_subject_stub,
    subject_records_to_frame,
)
from tvbtoolkit.analysis.luppi2022 import (
    build_annotation_template,
    compute_fc_matrix,
    edge_rank_gradient,
    matrix_spearman_similarity,
    nodal_strength,
    redundancy_synergy_rank_gradient,
    save_annotation_template,
    summarize_within_between,
    threshold_top_density,
    upper_triangle_values,
    weighted_global_efficiency,
    weighted_modularity,
)
from tvbtoolkit.analysis.dynamic_phiid import (
    build_subject_dynamic_features,
    centroid_connectivity_similarity,
    compare_centroids_to_connectomes,
    connectivity_vectors_from_records,
    edge_vector_to_matrix,
    fit_dynamic_state_model,
    fit_incremental_pca,
    iter_subject_feature_blocks,
    load_local_phiid_index,
    load_local_phiid_subject,
    parse_local_phiid_name,
    pool_reduced_dynamic_features,
    reconstruct_state_centroids,
    score_kmeans_range,
    split_reconstructed_features,
)
from tvbtoolkit.analysis.phiid_var_sweep import (
    MEASURE_COLORS,
    MEASURE_LABELS,
    MEASURE_ORDER,
    load_var_noise_sweep,
    plot_noise_sweep_publication,
    plot_noise_sweep_replicates,
    summarize_sweep,
    sweep_long_form,
)
from tvbtoolkit.analysis.three_node_adex_phiid import (
    ATOM_ORDER as THREE_NODE_ATOM_ORDER,
    MEASURE_ORDER as THREE_NODE_MEASURE_ORDER,
    load_three_node_phiid_index,
    load_three_node_phiid_output,
    parse_three_node_output_name,
    plot_three_node_hypothesis_clean,
    plot_three_node_hypothesis_summary,
    plot_three_node_matrix_grid,
    summarize_three_node_outputs,
)
from tvbtoolkit.analysis.two_node_adex_phiid import (
    MEASURE_ORDER as TWO_NODE_MEASURE_ORDER,
    load_two_node_phiid_index,
    load_two_node_phiid_output,
    parse_two_node_output_name,
    plot_two_node_g_noise_heatmaps,
    plot_two_node_g_noise_heatmaps_publication,
    plot_two_node_publication,
    plot_two_node_replicates,
    plot_two_node_sts_only,
    summarize_two_node_outputs,
)

__all__ = [
    # brain_states
    "BrainStateSummary",
    "phase_patterns",
    "cluster_brain_states",
    "summarize_brain_states",
    "centers_to_matrices",
    "brain_state_metrics_dict",
    "sfc_sort_centroids",
    # spectral
    "PSDResult",
    "ValidityResult",
    "psd_per_region",
    "dominant_frequency",
    "phase_coherence_validity",
    # state_alignment
    "AlignmentResult",
    "safe_pearson",
    "centroid_similarity_matrix",
    "fit_state_templates",
    "align_states_to_templates",
    # dynamics
    "load_survival_arrays",
    "plot_survival_heatmap",
    # phiid
    "PHIID_ATOMS",
    "PRIMARY_ATOMS",
    "PUBLICATION_COHORT_ORDER",
    "LEGACY_REFERENCE_PATHS",
    "sanitize_subject_stub",
    "subject_records_to_frame",
    "export_phiid_subject_inputs",
    "build_matlab_batch_command",
    "parse_phiid_output_name",
    "load_phiid_matrix",
    "load_phiid_index",
    "average_atom_matrices_by_group",
    "save_group_average_outputs",
    "default_atom_cmap",
    "format_roi_label_compact",
    "compact_roi_labels",
    "publication_atom_cmap",
    "plot_phiid_matrix",
    "plot_group_average_grid",
    "plot_publication_cohort_grid",
    "plot_publication_method_comparison_grid",
    # luppi2022
    "build_annotation_template",
    "compute_fc_matrix",
    "upper_triangle_values",
    "matrix_spearman_similarity",
    "nodal_strength",
    "threshold_top_density",
    "redundancy_synergy_rank_gradient",
    "edge_rank_gradient",
    "weighted_global_efficiency",
    "weighted_modularity",
    "summarize_within_between",
    "save_annotation_template",
    # dynamic_phiid
    "parse_local_phiid_name",
    "load_local_phiid_subject",
    "load_local_phiid_index",
    "edge_vector_to_matrix",
    "build_subject_dynamic_features",
    "iter_subject_feature_blocks",
    "fit_incremental_pca",
    "pool_reduced_dynamic_features",
    "score_kmeans_range",
    "fit_dynamic_state_model",
    "split_reconstructed_features",
    "reconstruct_state_centroids",
    "connectivity_vectors_from_records",
    "centroid_connectivity_similarity",
    "compare_centroids_to_connectomes",
    # phiid_var_sweep
    "MEASURE_ORDER",
    "MEASURE_LABELS",
    "MEASURE_COLORS",
    "load_var_noise_sweep",
    "sweep_long_form",
    "summarize_sweep",
    "plot_noise_sweep_publication",
    "plot_noise_sweep_replicates",
    # three_node_adex_phiid
    "THREE_NODE_MEASURE_ORDER",
    "THREE_NODE_ATOM_ORDER",
    "parse_three_node_output_name",
    "load_three_node_phiid_output",
    "load_three_node_phiid_index",
    "summarize_three_node_outputs",
    "plot_three_node_matrix_grid",
    "plot_three_node_hypothesis_clean",
    "plot_three_node_hypothesis_summary",
    # two_node_adex_phiid
    "TWO_NODE_MEASURE_ORDER",
    "parse_two_node_output_name",
    "load_two_node_phiid_output",
    "load_two_node_phiid_index",
    "summarize_two_node_outputs",
    "plot_two_node_g_noise_heatmaps",
    "plot_two_node_g_noise_heatmaps_publication",
    "plot_two_node_publication",
    "plot_two_node_replicates",
    "plot_two_node_sts_only",
]
